# Generated by Django 4.0.4 on 2023-05-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
